name: Enviar correos por cambios en ramas

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar correo al realizar cambios
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587  # Puerto para TLS
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cambios subidos a rama ${{ github.ref_name }}
          body: |
            Hola,

            Se han subido cambios a la rama: ${{ github.ref_name }}.

            Saludos,
            Tu equipo
          to: destinatario@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true  # Habilita TLS
