name: Send Email on Branch Changes

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Cambios subidos a rama ${{ github.ref_name }}
        body: |
          Hola,
          Se han realizado cambios en la rama: ${{ github.ref_name }}.
          Verifica el repositorio para más detalles.
        to: destinatario@example.com
        from: ${{ secrets.EMAIL_USERNAME }}
